### ISSUE TITLE
How to create word embeddings for a random sample text using sense spectrum?

### ISSUE THREAD

**Issue by reallysaurabh** [canlinzhang/Sense-Spectrum#1]

**Comment by canlinzhang** [comment]
Hi, the sense spectrum is for noun and verb senset in WordNet. If you want to create sense spectrum for general word embeddings, you need to first discover the corresponding sensets for that word in WordNet. For example, word "eat" can be related to v.01.eat, v.02.eat, etc in WordNet. 

There may be multiple sensets for a word. Obtaining spectrum for each of these sensets and average these spectra dimension-wise, you can finally get the spectrum for the word.

Please refer to my paper "Dense Embeddings Preserving the Semantic Relationships in WordNet" (https://ieeexplore.ieee.org/abstract/document/9892238) for a detailed introduction. Sorry for not updating this repo in time. I will connect the repo with the paper shortly.

**Comment by reallysaurabh** [comment]
Can you update the code with a function that takes a synset as an input and returns its embedding as output?

**Comment by canlinzhang** [comment]
Yes, working on that. Should be able to re-form the code by tomorrow or this weekend. Thanks!

**Comment by reallysaurabh** [comment]
Are there any updates on this?

**Comment by canlinzhang** [comment]
Yes, working on updating the code and generating functions. Give me another few hours.

**Comment by canlinzhang** [comment]
Dear Author:

Here is the script for obtaining noun and verb synset spectrum for a given word. For example, we can obtain the noun and verb synset spectrum for the word 'dog' by implementing the following script:
```
from obtain_sense_spectra import ObtainSpectrum

Class = ObtainSpectrum('synset_spactra/noun_synset_spectra.pickle', 'synset_spactra/verb_synset_spectra.pickle')

noun_spec, verb_spec = Class.obtain_spectrum_for_word('dog')
```

Here, `noun_spec` is the average of the noun synset spectra related to 'dog'. To be specific, by evaluating `nltk wordnet`, we can see the noun synset related to 'dog' are `dog.n.01`, `frump.n.01`, `dog.n.03`, `cad.n.01`, `frank.n.02`, `pawl.n.01` and `andiron.n.01`. Then, the above script will obtain the spectrum for each of these synsets, average the obtained spectra dimension-wise, and then output the average spectra as `noun_spec`. The `verb_spec` is obtained similarly from the verb synsets related to 'dog', which is only `chase.v.01`.

On the other hand, if you already get the synset (say, 'dog.n.01') and just want to obtain the corresponding spectrum, simply implement the same class as above and run
```
spec = Class.obtain_spectrum_for_synset('dog.n.01')
```

Sorry for the delay. Thank you so much for your patience! Please let me know how is the implementation and or if you have other questions.

**Comment by reallysaurabh** [comment]
Working as expected. Thanks a lot!
